
-- Generated by ORDS REST Data Services 25.4.0.r3441128
-- Schema: WKSP_AQS  Date: Sun Jan 18 10:12:18 2026 
--
        
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'aqs',
      p_auto_rest_auth      => TRUE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'ejemplo_header',
      p_base_path      => '/ejemplo_header/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ejemplo_header',
      p_pattern        => 'manuales',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ejemplo_header',
      p_pattern        => 'manuales',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
  htp.p(''user-agent: '' || owa_util.get_cgi_env(''HTTP_USER_AGENT''));
  htp.br;
  htp.p(''content-type: '' || owa_util.get_cgi_env(''content-type''));
  htp.br;
  htp.p(''accept-language: '' || owa_util.get_cgi_env(''accept-language''));
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ejemplo_header',
      p_pattern        => 'all_headers',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ejemplo_header',
      p_pattern        => 'all_headers',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'BEGIN
  FOR i IN 1 .. owa.num_cgi_vars LOOP
    htp.p(
      owa.cgi_var_name(i) || '' = '' ||
      owa.cgi_var_val(i)
    );
    --htp.br;
  END LOOP;

END;');

  ORDS.CREATE_ROLE(
      p_role_name=> 'oracle.dbtools.role.autorest.WKSP_AQS');
  ORDS.CREATE_ROLE(
      p_role_name=> 'oracle.dbtools.role.autorest.any.WKSP_AQS');
  l_roles(1) := 'oracle.dbtools.autorest.any.schema';
  l_roles(2) := 'oracle.dbtools.role.autorest.WKSP_AQS';
  l_patterns(1) := '/metadata-catalog/*';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'oracle.dbtools.autorest.privilege.WKSP_AQS',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'WKSP_AQS metadata-catalog access',
      p_description    => 'Provides access to the metadata catalog of the objects in the WKSP_AQS schema.',
      p_comments       => NULL); 

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;

  l_roles(1) := 'SODA Developer';
  l_patterns(1) := '/soda/*';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'oracle.soda.privilege.developer',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => NULL,
      p_description    => NULL,
      p_comments       => NULL); 

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;


COMMIT;

END;
